In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
%matplotlib inline

### Loading the Dataset

In [2]:
data_train = pd.read_csv("data/http_train.csv")
data_test = pd.read_csv("data/http_test.csv")

X_train = data_train.drop(data_train.columns[-1],axis=1)
y_train = data_train.iloc[:,-1]

X_test = data_test.drop(data_test.columns[-1],axis=1)
y_test = data_test.iloc[:,-1]
data_train.head()

0         1         2  3
0 -2.302585  5.638710  6.853405  0
1 -2.302585  5.727173  7.099284  0
2 -2.302585  5.204556  8.565431  0
3 -2.302585  5.333202  7.319269  0
4 -2.302585  5.464255  7.368403  0

### Training, Making Predictions, Evaluation

In [3]:
def svm(ker):
    #training the model
    svclassifier = SVC(kernel=ker)
    svclassifier.fit(X_train, y_train)
    #making predictions
    y_pred = svclassifier.predict(X_test)
    #evaluating the model
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

In [4]:
#Linear Kernel
svm('linear')

[[113056      2]
 [     3    439]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    113058
           1       1.00      0.99      0.99       442

    accuracy                           1.00    113500
   macro avg       1.00      1.00      1.00    113500
weighted avg       1.00      1.00      1.00    113500



In [5]:
#Gaussian Kernel
svm('rbf')

/Applications/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[113058      0]
 [     3    439]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    113058
           1       1.00      0.99      1.00       442

    accuracy                           1.00    113500
   macro avg       1.00      1.00      1.00    113500
weighted avg       1.00      1.00      1.00    113500



In [6]:
#Sigmoid Kernel
svm('sigmoid')

/Applications/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[112760    298]
 [   439      3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    113058
           1       0.01      0.01      0.01       442

    accuracy                           0.99    113500
   macro avg       0.50      0.50      0.50    113500
weighted avg       0.99      0.99      0.99    113500



In [7]:
def svm_poly():
    #training the model
    svclassifier = SVC(kernel='poly', degree=8)
    svclassifier.fit(X_train, y_train)
    #making predictions
    y_pred = svclassifier.predict(X_test)
    #evaluating the model
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

In [ ]:
#Polynomial Kernel
svm_poly()